
name: Build

on:
  push:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Run build script
      run: bash build.sh

    - name: Upload artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: snlncreceiver
        path: dist/snlncreceiver

    - name: Upload artifact on release
      if: github.event_name == 'release'
      uses: actions/upload-artifact@v3
      with:
        name: snlncreceiver
        path: dist/snlncreceiver

    - name: Upload to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/snlncreceiver
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}